stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    # 下载阿里巴巴 JDK 11
    - wget https://github.com/alibaba/dragonwell11/releases/download/dragonwell-extended-11.0.18.14_jdk-11.0.18-ga/Alibaba_Dragonwell_Extended_11.0.18.14.9_x64_linux.tar.gz
    - docker build -t dragonwell11:11.0.18.14-Extended .
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker tag dragonwell11:11.0.18.14-Extended $DOCKER_USERNAME/dragonwell11:11.0.18.14-Extended
    - docker images
    - docker push $DOCKER_USERNAME/dragonwell11:11.0.18.14-Extended
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
  rules:
    - if: $CI_COMMIT_TAG
